---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash
  namespace: proxy
  labels:
    app: clash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
      - name: clash
        command: ["/bin/sh", "-c"]
        args: ["/clash -f /root/clash/clash.yaml"]
        image: johnatmars/clash-armv8:v1.8.2
        ports:
        - containerPort: 7890
        volumeMounts:
          - mountPath: /root/clash
            name: config
      volumes:
        - name: config
          hostPath:
            path: /home/john/clash
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                  - slave
---
apiVersion: v1
kind: Service
metadata:
  name: clash-service
  namespace: proxy
spec:
  type: LoadBalancer
  selector:
    app: clash
  ports:
    - port: 7890
      targetPort: 7890
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32100
      protocol: TCP
